### PR TITLE
Adapt w.r.t. coq/coq#16910.

### PR DESCRIPTION
**Pull request by ppedrot**
This should be backwards compatible at least up to 8.16.

### CODE REVIEW

**Comment by ppedrot** [comment]
Ping @bcpierce00

**Comment by bcpierce00** [comment]
Sorry for getting to this slowly -- it's going to take a bit of time
because I have to back-port the changes to the main sfdev repo (from which
this public repo is generated).

To avoid this step in the future, we should give you direct access to the
sfdev repo...

**Comment by ppedrot** [comment]
No problem, the upstream PR is not urgent. I just wanted to double-check this didn't fly under the radar.

**Comment by SkySkimmer** [comment]
I made the sfdev version https://github.com/DeepSpec/sfdev/pull/524

**Comment by SkySkimmer** [comment]
sfdev version was merged, please merge this one or otherwise update the public repo @bcpierce00

**Comment by bcpierce00** [comment]
Yes, thanks -- had not forgotten this bit, but I got slowed down by needing to update the CI infrastructure a bit.  

I'll just go ahead and merge this now so you can stop worrying about it, but in the next day or two I should be able to autogenerate this version from the sfdev repo.

**Pull request merged**
