### PR TITLE
build(ci): Build and push Docker containers

### PR DESCRIPTION
**Pull request by wldhx**

### CODE REVIEW

**Review by liyishuai — APPROVED** [review]

**Comment by bcpierce00** [comment]
The CI for this seems to be failing -- is this related to Andrew Appel's request to update the VST version in the CI?  (And what's the status of that? -- I'm afraid I've lost track...)

**Comment by liyishuai** [comment]
CI uses VST 2.8.
The current VC chapter requires 2.7.
DeepSpec/sfdev#336 updates VC to depend on 2.8, but that build is failing despite on VST 2.8.

Therefore, the roadmap is: Fix build in DeepSpec/sfdev#336 (caused by removal of `vc/_CoqProject`), and merge that PR. After deploying the new VC chapter to this repo and merging this PR, all builds should be fixed.

**Comment by bcpierce00** [comment]
Thank you, Yishuai!

Not sure why the _CoqProject in /vc got deleted -- I've asked Andrew -- but
it's easy to regenerate ('make _CoqProject').  I'll try doing this and
re-running CI locally...

**Comment by bcpierce00** [comment]
Eeek -- CI is now failing in a way that I haven't seen before (and very early)...
```
> make ci

circleci config process .circleci/config.yml > .circleci/process.yml
⠼ Checking for updates... panic: semver: Parse(0.1.15338_1): Invalid character(s) found in patch number "15338_1"

goroutine 1 [running]:
github.com/blang/semver.MustParse(0xc000110190, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/circleci-20210505-3845-10y4uvu/pkg/mod/github.com/blang/semver@v3.5.1+incompatible/semver.go:319 +0x245
github.com/CircleCI-Public/circleci-cli/update.checkFromHomebrew(0xc0001cca20, 0xc0001cca20, 0x0)
	/private/tmp/circleci-20210505-3845-10y4uvu/src/github.com/CircleCI-Public/circleci-cli/update/update.go:93 +0x265
github.com/CircleCI-Public/circleci-cli/update.CheckForUpdates(0x17e4739, 0x17, 0x17e9531, 0x1c, 0x189f0d0, 0x9, 0x189ed70, 0x8, 0x0, 0xc00023bcf8, ...)
	/private/tmp/circleci-20210505-3845-10y4uvu/src/github.com/CircleCI-Public/circleci-cli/update/update.go:46 +0x226
github.com/CircleCI-Public/circleci-cli/cmd.checkForUpdates(0xc000226480, 0x1, 0xc0001b0708)
	/private/tmp/circleci-20210505-3845-10y4uvu/src/github.com/CircleCI-Public/circleci-cli/cmd/check.go:37 +0x27a
github.c(...)
	/private/tmp/circleci-20210505-3845-10y4uvu/src/github.com/CircleCI-Public/circleci-cli/cmd/root.go:184
github.com/CircleCI-Public/circleci-cli/cmd.MakeCommands.func1(0xc00034a280, 0xc000334fa0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/circleci-20210505-3845-10y4uvu/src/github.com/CircleCI-Public/circleci-cli/cmd/root.go:97 +0x2d
github.com/spf13/cobra.(*Command).execute(0xc00034a280, 0xc000334f60, 0x1, 0x1, 0xc00034a280, 0xc000334f60)
	/private/tmp/circleci-20210505-3845-10y4uvu/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:805 +0x582
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fdb80, 0x10014b0, 0x0, 0x0)
	/private/tmp/circleci-20210505-3845-10y4uvu/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/circleci-20210505-3845-10y4uvu/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/CircleCI-Public/circleci-cli/cmd.Execute()
	/private/tmp/circleci-20210505-3845-10y4uvu/src/github.com/CircleCI-Public/circleci-cli/cmd/root:37 +0x2a
main.main()
	/private/tmp/circleci-20210505-3845-10y4uvu/src/github.com/CircleCI-Public/circleci-cli/main.go:9 +0x25
make: *** [.circleci/process.yml] Error 2
~/s> ```

**Comment by liyishuai** [comment]
Consider reinstalling the CircleCI CLI? I have version 0.1.15384+149d854 via Homebrew.

**Comment by bcpierce00** [comment]
Now I get this:

make ci

circleci local execute -c .circleci/process.yml --job "coq 8_12"
Error: No configuration was found in your project. Please refer to
https://circleci.com/docs/2.0/ to get started with your configuration.
make: *** [ci] Error 255

**Comment by liyishuai** [comment]
Maybe your `.circleci/process.yml` was corrupted due to the previous failing run. Try removing `.circleci/process.yml` and rerun `make ci`.

**Comment by bcpierce00** [comment]
Yes, that's better!  :-)

**Comment by bcpierce00** [comment]
... but I'm still having trouble understanding what's happening.  If I add a _CoqProject to the /vc directory and do `make ci` I still get an error that there is no _CoqProject when it tries to copy all the files to the `terse` build directory...
```
Rebuilding HTML files in ../_built/vc/terse...
cp -Rf README /home/coq/project/common _CoqProject cfiles-bitsize sumarray.c reverse.c append.c stack.c strlib.c hash.c stdlib.c stdlib2.c stdlib.h stack2.c stack2.h triang2.c triang2.h main2.c chain.gif sumarray32.v reverse32.v append32.v stack32.v strlib32.v hash32.v sumarray64.v reverse64.v append64.v stack64.v strlib64.v hash64.v stack232.v stdlib232.v stdlib32.v triang232.v main232.v stack264.v stdlib264.v stdlib64.v triang264.v main264.v VC.pdf Reverse-Slides.pdf ../_built/vc/terse
cp: cannot stat '_CoqProject': No such file or directory
make[4]: *** [../Top.Makefile:395: tgt-index-aux] Error 1
```
Am I doing this the wrong way?  (E.g., is `make ci` getting files from the local filesystem, or from GitHub?)

**Comment by liyishuai** [comment]
The documentation says the default is to use the local path as-is, but you could try specifying the Git revision by `--revision`: https://circleci-public.github.io/circleci-cli/circleci_local_execute.html

**Comment by bcpierce00** [comment]
Weird.  Is `make ci` working for you?

**Comment by liyishuai** [comment]
`make _CoqProject; make` worked on my machine. I've updated sfdev CI to build `_CoqProject` before everything starts.

**Comment by bcpierce00** [comment]
Still not quite there.  Doing `make ci` grinds for a long time and then fails -- see attached.

[make-ci-output.txt](https://github.com/DeepSpec/sf/files/6729431/make-ci-output.txt)

**Comment by liyishuai** [comment]
Weird. I've replicated the failure. The entire build worked fine on 8.12, and failed on 8.13. Something needs to be fixed, but Andrew's PR seems ready to go.

**Comment by bcpierce00** [comment]
OK, very good -- I'll merge it.  Thank you.

**Comment by bcpierce00** [comment]
One last double-check before merging: Is not working on 8.13 going to mess
up the Coq team's CI?  Should we wait till we've figured out this bit?

**Comment by liyishuai** [comment]
[Coq CI](https://github.com/coq/coq/blob/master/dev/ci/ci-sf.sh) only checks LF PLF VFA volumes, so it won't be broken by VC changes.

**Comment by bcpierce00** [comment]
Ah.  We should probably do something about that!  But in the meantime, I
will merge the PR.

**Comment by bcpierce00** [comment]
(I guess the 8.13 issue will cause the master branch CI to fail.  But it's failing at the moment too, so this doesn't make anything worse...)

**Pull request merged**
