### PR TITLE
Adapt w.r.t. coq/coq#16904.

### PR DESCRIPTION
**Pull request by ppedrot**
Not sure I did everything required, the HTML code still mentions elimtype.

### CODE REVIEW

**Comment by charguer** [comment]
The changes are good. @bcpierce00 please merge.

@ppedrot to avoid nontrivial package dependencies for SF users, we include files extracted from the sources of the TLC library in the PLF and SLF volumes. The downside is patches on TLC for Coq-CI may need to be applied 3 times (once in TLC, and twice in SF). In case of more involved changes that the one from this PR, you can contact me, so that I can synchronize SF files with those from TLC. Beware that the two might not always be in perfect sync, because I do not modify SF files after every  commit in TLC, as doing so requires recompiling PLF and SLF entirely.

**Comment by bcpierce00** [comment]
Merged!  I assume you'll also make these changes in PLF and SLF, Arthur, so they're not overwritten here by the next release.

**Comment by charguer** [comment]
This PR does make the change in PLF/SLF. The same changes were applied in TLC. We should therefore be safe on the next import from TLC to PLF/SLF. Thanks

**Comment by bcpierce00** [comment]
Sorry -- I meant in the sfdev repo.  As you say, this should happen the
next time we import from TLC, but I guess that should be before a next
release of PLF or SLF.

    - B

**Pull request merged**
